# 送料柜自动续料系统配置文件

# CAN通信配置
can:
  # CAN接口名称，通常为can0或can1，取决于硬件配置
  interface: can1
  
  # CAN总线波特率，需与送料柜控制器一致，单位：bps
  bitrate: 1000000

# Klipper/Moonraker连接配置
klipper:
  # Moonraker API URL，默认使用本机地址
  # 如果Moonraker运行在不同主机，请修改为对应的IP地址
  moonraker_url: http://localhost:7125
  
  # 状态更新间隔（秒），影响状态检测的响应速度
  # 除了WebSocket实时监听外，还会每隔此时间主动查询一次状态
  # 值越小响应越快，但会增加系统负载
  update_interval: 5.0

# 挤出机配置
extruders:
  # 挤出机数量
  count: 2
  
  # 默认活跃挤出机（0=左，1=右）
  active: 0
  
  # 挤出机到料管的映射关系
  mapping:
    0: 0  # 挤出机0（左）对应料管0
    1: 1  # 挤出机1（右）对应料管1
  
  # 左右喷头对应的送料柜料管
  left:
    tube: 0  # 左喷头对应的送料柜料管编号
  right:
    tube: 1  # 右喷头对应的送料柜料管编号

# 断料检测配置
filament_runout:
  # 是否启用断料检测
  enabled: true
  
  # 传感器引脚，可选，留空则使用Klipper内置检测
  # 示例: "gpiochip0/gpio16"
  sensor_pin: null
  
  # 断料传感器配置列表
  sensors:
    - name: "Filament_Sensor0"  # 传感器名称，需与Klipper配置中的名称一致
      extruder: 0               # 对应的挤出机索引（0=左，1=右）
    - name: "Filament_Sensor1"  # 传感器名称，需与Klipper配置中的名称一致
      extruder: 1               # 对应的挤出机索引（0=左，1=右）
klipper:
  moonraker_url: http://localhost:7125
  update_interval: 5.0

# 日志配置
logging:
  backup_count: 5
  console_output: true
  level: INFO
  log_dir: /home/mingda/printer_data/logs
  
  # 是否输出到控制台（开发调试用）
  console_output: true
  
  # 单个日志文件最大大小（字节），默认10MB
  max_file_size: 10485760  # 10 * 1024 * 1024
  
  # 保留的日志文件数量（轮转后）
  backup_count: 5
  
  # 日志文件最大保留天数（自动清理）
  max_age_days: 30
  max_file_size: 10485760
safety:
  # 送料请求超时时间（秒），超过此时间仍未收到响应则报错
  request_timeout: 60.0
  
  # 是否在检测到错误时自动尝试恢复
  auto_recovery: true
  
  # 恢复重试次数
  recovery_attempts: 3
  
  # 重试间隔（秒）
  recovery_interval: 10.0
  request_timeout: 60.0
system:
  # 守护进程模式，设置为true则在后台运行
  daemon: false

# RFID配置
rfid:
  # 是否启用RFID功能
  enabled: true
  
  # 是否自动设置耗材温度
  auto_set_temperature: false
  
  # RFID数据保存目录
  data_dir: /home/mingda/printer_data/rfid
  
  # RFID传输超时时间（秒）
  transfer_timeout: 30.0
  
  # 会话清理间隔（秒）
  cleanup_interval: 60

# Spoolman集成配置
spoolman:
  # 是否启用Spoolman集成
  enabled: true
  
  # Spoolman服务器URL
  url: http://localhost:7912
  
  # 是否自动同步RFID数据到Spoolman
  auto_sync_rfid: true
  
  # 同步失败时的重试次数
  retry_count: 3
  
  # 重试间隔（秒）
  retry_interval: 5.0 